server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: develup12345@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/easy?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.practice.logincrud
  configuration:
    map-underscore-to-camel-case: true
